spring.data.mongodb.uri=mongodb+srv://harshtolani11011lr_db_user:RQIeYWaQN5KPr94C@cluster0.hugdatb.mongodb.net/mydatabase?appName=Cluster0
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword